### ISSUE TITLE
GopherCon Brasil, Nov/4-5

### ISSUE THREAD

**Issue by carlisia** [catehstn/technically-speaking#101]
(Note: We require conferences to have code of conduct, and highly prefer those they pays travel expenses / speaker fee to speakers.)

### GopherCon Brasil
*Brazil's largest event dedicated to Go* 
 
Event date: **Nov/4th and 5th**, with an all-day workshop on the 6th
Location: **Florianopolis, Brazil**
Submission deadline: 10/10/2016
Travel expenses covered: No, unfortunately
[GopherCon Brasil website](https://2016.gopherconbr.org/en/)
[cfp submission](https://www.papercall.io/gopherconbrazil2016)
[@gopherconbrasil](https://twitter.com/gopherconbrasil)

[Code of  Conduct](https://2016.gopherconbr.org/en/conduct/)

**Comment by chiuki** [comment]
Sorry we don't include conferences that flat out say no to helping speakers. We understand that there may not be budget to support everyone, but we prefer to include conferences that at least make an effort on a case-by-case basis.
