### ISSUE TITLE
2016-11-03: Mobile Era 2016 

### ISSUE THREAD

**Issue by webmaxru** [catehstn/technically-speaking#103]
### Mobile Era 2016
*Norway's first conference for mobile developers. The conference will cover Android, iOS, Hybrid and Mobile Web development from both a design and development perspective.* 
 
Event date: November 3-4, 2016
Location: Oslo, Norway
Submission deadline: August 15, 2016
Travel expenses covered: Yes
[mobileera.rocks](http://mobileera.rocks/)
[cfp](http://mobileera.rocks/call-for-papers/)
[@mobileeraconf](https://twitter.com/mobileeraconf)

**Comment by chiuki** [comment]
Already included: http://tinyletter.com/techspeak/letters/technically-speaking-july-19th-2016
