### ISSUE TITLE
2016-09-15: Ela Conf

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#108]
### Ela Conf
*Empowering more women to be leaders in tech* 
 
Event date: November 4 - 5, 2016
Location: Philadelphia, PA
Submission deadline: September 15, 2016
Travel expenses covered: Not specified. Ask.
[elaconf.com](http://elaconf.com)
[elaconf.com/proposals](http://elaconf.com/proposals)
[@elaconf](https://twitter.com/elaconf)

**Comment by yprabhu** [comment]
I had the opportunity to attend and speak at ElaConf in their inaugural year. They're back again this time and it's sure to be even more awesome than last time!  It's organized by a group of wonderful women who contribute a lot to the community and all proceeds go to GirlDevelopIt. The talks last year touched on self-care, management, salary negotiation, public speaking, starting companies, community building and so on. It's a smaller scale conference which means you get to meet and hang out with more attendees. 95% said they'll attend again and I'm definitely one of them!

**Comment by chiuki** [comment]
Published in Edition 89 (PR #114)
