### ISSUE TITLE
2016-09-16: Clojure/conj

### ISSUE THREAD

**Issue by lynngrogan** [catehstn/technically-speaking#111]
### Clojure/conj
*7th Annual Clojure/conj Conference* 
 
Event date: December 1 - 3, 2016
Location: Austin, TX
Submission deadline: September 16, 2016
Travel expenses covered: Yes
[2016.clojure-conj.org](http://2016.clojure-conj.org/)
[2016.clojure-conj.org/cfp](http://2016.clojure-conj.org/cfp/)
[@clojure_conj](https://twitter.com/clojure_conj)

**Comment by chiuki** [comment]
Included in Edition 90 (PR #118)
