### ISSUE TITLE
2016-09-05: EmpireNode

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#120]
### EmpireNode
*NYC's largest community run Node.js conference* 
 
Event date: November 7, 2016
Location: New York City, NY
Submission deadline: September 5, 2016
Travel expenses covered: Yes
[2016.empirenode.org](http://2016.empirenode.org/)
[goo.gl/IlTtdE](https://goo.gl/IlTtdE)
[@empirenode](https://twitter.com/empirenode)

**Comment by noopkat** [comment]
I had the opportunity to speak at the last EmpireNode. I noticed it had one of the most diverse speaker lineups compared to other NodeJS conferences being run that year. All talks were live captioned, and the emcee was fantastic at helping attendees get to know the speakers in a candid way. The organisers set a really good example for other conferences to follow. The talks touched on topics such as public data projects, NodeJS robotics, desktop applications made in NodeJS, and microservices. I felt there was a talk for everyone's interests!
