### ISSUE TITLE
2016-08-31: PyCon Canada

### ISSUE THREAD

**Issue by aarose** [catehstn/technically-speaking#122]
### PyCon Canada
PyCon Canada is the largest Canadian python conference intended for networking and collaboration in the python community.
 
Event date: November 12, 2016 - November 13, 2016
Location: Toronto, Canada
Submission deadline: August 31, 2016
Travel expenses covered: On a case-by-case basis
[https://2016.pycon.ca/en/](https://2016.pycon.ca/en/)
[https://cfp.pycon.ca/](https://cfp.pycon.ca/)
[@pyconca](https://twitter.com/pyconca)

**Comment by aarose** [comment]
Sorry, is it too late for this to be included in tomorrow's newsletter? I know the CFP closes very soon, but I'd love for there to be more exposure that FA is a possibility this year!

**Comment by chiuki** [comment]
@aarose What is FA?

**Comment by aarose** [comment]
@chiuki oh whoops, financial aid!

**Comment by aarose** [comment]
thanks so much!! I was so excited to see it there 😄
