### ISSUE TITLE
2016-09-27: Product Leaders Unconference CFP

### ISSUE THREAD

**Issue by stelianamoraru** [catehstn/technically-speaking#133]
### Product Leaders Unconference
*Share experience and knowledge with European product practitioners*
 
Event date: November 24 - 25, 2016
Location: Bucharest, Romania
Submission deadline: September 27, 2016
Travel expenses covered: 2 nights of accomodations. Up to 200 Eur travel expenses covered
[productleaders.co](http://productleaders.co)
[productleaders.co/call-for-speakers](http://productleaders.co/call-for-speakers/)
[@mozaicworks](https://twitter.com/mozaicworks)

**Comment by chiuki** [comment]
@stelianamoraru What do you mean when you say travel expenses are partially covered? Are there more details on the site / on twitter? Thanks!

**Comment by stelianamoraru** [comment]
We cover accommodation for 2 days. For the travel, I am still waiting for the final approval for the budget. At previous events, we covered either wholly or partially the tickets. I will update the announce as soon as I have a confirmation. Thank you!
