### ISSUE TITLE
How I survived my first big conference talk

### ISSUE THREAD

**Issue by shem8** [catehstn/technically-speaking#153]
I'm not sure if you're accepting link suggestions but if you do-
I really inspired from your newslater and in the last year I starting practicing in public speaking. Last month was my first big conference talk. I wrote a bit about my experience [here](https://medium.com/@shemag8/how-i-survived-my-first-big-conference-talk-532d337d439a)

Thanks!

**Comment by chiuki** [comment]
@shem8 Yes we do take links! And thank you for the blog post.
