### ISSUE TITLE
2016-11-06: MicroXchg 2017

### ISSUE THREAD

**Issue by cpoepke** [catehstn/technically-speaking#155]
### MicroXchg 2017
*The Microservices Conference in Berlin*
 
Event date:  February 16 - 17, 2017
Location: Kalkscheune, Berlin, Germany
Submission deadline: November 6, 2016
Travel expenses covered: Depends. Add a comment on CFP form.
[microxchg.io/2017](http://microxchg.io/2017/index.html)
[microxchg.io/2017#call-for-papers](http://microxchg.io/2017/index.html#call-for-papers)
[@microxchg](https://twitter.com/@microxchg)

**Comment by chiuki** [comment]
@cpoepke Can you clarify "Depends"? How do speakers request help with travel expenses? Thanks!

**Comment by cpoepke** [comment]
They can add a comment in the cfp submissions form, if they have a case for travel expenses. We are a community organised conference and have a very low entrance fee. Hence we can only pay in special cases and do not advertise it.
