### ISSUE TITLE
Giveaway

### ISSUE THREAD

**Issue by catehstn** [catehstn/technically-speaking#210]
https://twitter.com/i/moments/793180454224408576

**Comment by catehstn** [comment]
@kwugirl - do you want to pick the winners? <3

**Comment by kwugirl** [comment]
Raimon Ràfols - https://twitter.com/rrafols/status/790878478317027328
Lucy Bain - https://twitter.com/lucykbain/status/790977030938439681
Kelley Robinson - https://twitter.com/kelleyrobinson/status/791011253963493377
Antoinette Authedna - https://twitter.com/ant_auth/status/793632208107900929
Rizwan Javaid - https://twitter.com/rizwanjavaid/status/793665057607458816

Note: Kelley is a personal friend but I had pulled out the names and did a random selection on those, hope that's ok! I think there's a lovely theme of "firsts" of all kinds for people in the past year, from first conference talks to keynotes!

**Comment by catehstn** [comment]
Amazing - replied to everyone directing them to email @arielnaomi - when we have everyone we can send it to A Book Apart. Just need address for physical book. If they want an ebook I guess platform and email to send it to.
