### ISSUE TITLE
2017-01-06: CoderCruise

### ISSUE THREAD

**Issue by EliW** [catehstn/technically-speaking#216]
### CoderCruise
*A WebTech Conference on a Cruise Ship* 
 
Event date: July 16-23, 2017
Location: New Orleans, Montego Bay, Grand Cayman, and Cozumel (aboard the Carnival Dream)
Submission deadline: January 6th, 2017
Travel expenses covered: No
[www.codercruise.com](https://www.codercruise.com)
[www.codercruise.com/call-for-speakers/](https://www.codercruise.com/call-for-speakers/)
[@oneforallevents](https://twitter.com/oneforallevents)

**Comment by chiuki** [comment]
Closing since the CFP deadline has passed.
