### ISSUE TITLE
2017-01-30: Web Rebels

### ISSUE THREAD

**Issue by troubalex** [catehstn/technically-speaking#233]
### Web Rebels
*A community driven conference for and by developers who love creating stuff using web technology. A member of the JSConf family of conferences.* 
 
Event date: June 1-2, 2017
Location: Oslo, Norway
Submission deadline:  January 30, 2017 at midnight CET
Travel expenses covered: Yes
[webrebels.org](https://www.webrebels.org/)
[Call for Papers on papercall.io](https://www.papercall.io/webreb2017)
[@web_rebels](https://twitter.com/web_rebels)

**Comment by chiuki** [comment]
Closing since the CFP deadline has passed.
