### ISSUE TITLE
Tech Talk Coaching!  Diversity scholarships available

### ISSUE THREAD

**Issue by gnarf** [catehstn/technically-speaking#242]
If you are submitting a link, please include:
---------------------------------------------
URL: https://twitter.com/brnnbrn/status/815661607351152640
Author name: Brenna O'Brien
Author twitter handle (if available): brnnbrn
Your twitter handle (optional): gnarf

Short description of what you loved about it:

A) I love Brenna's talks
B) I think many readers might want to sponsor, or take advantage of some free coaching for diverse would-be speakers.

**Comment by catehstn** [comment]
Thanks for the suggestion - we really appreciate it.
