### ISSUE TITLE
Own Your Expertise - Workshop January 21 in San Francisco

### ISSUE THREAD

**Issue by kathrynwp** [catehstn/technically-speaking#246]
Own Your Expertise is a [free, all-day workshop taking place in San Francisco on January 21](https://www.eventbrite.com/e/own-your-expertise-san-francisco-jan-2017-tickets-30216274691) that aims to help participants learn how to "present yourself as an expert, and get an intro to writing, speaking, and coding for open source." It incorporates a workshop on Impostor Syndrome and ties into the [Write/Speak/Code](http://www.writespeakcode.com/)'s conference's 2017 theme: "Rise Up"

**Comment by chiuki** [comment]
Sorry this happened when we were taking a break :(
