### ISSUE TITLE
3 Things to Do With Your Hands When You Speak

### ISSUE THREAD

**Issue by catehstn** [catehstn/technically-speaking#281]
If you worry about what to do with your hands when speaking, [@sabinanawaz](http://twitter.com/sabinanawaz) has you covered with three ideas [[read it](http://www.inc.com/sabina-nawaz/3-things-to-do-with-your-hands-when-you-speak.html)][tweet it].

**Comment by elioqoshi** [comment]
@catehstn link doesn't work :/
