### ISSUE TITLE
2017-05-25: PyOhio

### ISSUE THREAD

**Issue by krantzinator** [catehstn/technically-speaking#286]
### PyOhio
*A **free** annual conference for Python programmers in and around Ohio, the entire Midwest, maybe even the whole world.* 
 
Event date: July 29 - 30, 2017
Location: Columbus, OH
Submission deadline: May 25, 2017
Travel expenses covered: no (100% volunteer run and led conference)
[pyohio.org](http://pyohio.org)
[pyohio.org/call-for-proposals](http://pyohio.org/call-for-proposals/)
[@PyOhio](https://twitter.com/pyohio)

**Comment by chiuki** [comment]
Sorry we don't include conferences that flat out say no to helping speakers. We understand that there may not be budget to support everyone, but we prefer to include conferences that at least make an effort on a case-by-case basis.
