### ISSUE TITLE
2017-03-25: JuliaCon 2017

### ISSUE THREAD

**Issue by vchuravy** [catehstn/technically-speaking#292]
### JuliaCon 2017
The yearly community meetup for the community around Julia!
 
Event date: June 20th-24th 2017
Location: Berkeley, California, USA
Submission deadline: March 25th, 11:59pm AOE (UTC-12)
Travel expenses covered: No 
[juliacon.org/2017](http://juliacon.org/2017)
[juliacon.org/2017/cfp](http://juliacon.org/2017/cfp)

**Comment by chiuki** [comment]
Sorry we don't include conferences that flat out say no to helping speakers. We understand that there may not be budget to support everyone, but we prefer to include conferences that at least make an effort on a case-by-case basis.
