### ISSUE TITLE
2017-03-28: GORUCO

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#301]
### GORUCO
*New York's Regional Ruby Conference* 
 
Event date: June 24, 2017
Location: New York City, NY
Submission deadline: March 28, 2017
Travel expenses covered: $1200 travel reimbursement
[goruco.com](http://goruco.com/)
[cfp.goruco.com/events/2017](http://cfp.goruco.com/events/2017)
[@goruco](https://twitter.com/goruco)

**Comment by durhamka** [comment]
"GORUCO was a great conference! I felt very comfortable and the audience felt pretty diverse. I loved that they provided a fun speaker training the day before the conference. That was super helpful. The organizers were very accommodating and helpful! I would recommend speaking at this conference."
