### ISSUE TITLE
2017-03-20: !!Con

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#303]
### !!Con
*The joy, excitement, and surprise of computing* 
 
Event date: May 6 - 7, 2017
Location: New York City, New York
Submission deadline: March 20, 2017
Travel expenses covered: Financial assistance available
[bangbangcon.com](http://bangbangcon.com)
[bangbangcon.com/give-a-talk.html](http://bangbangcon.com/give-a-talk.html)
[@bangbangcon](https://twitter.com/bangbangcon)

**Comment by lvgelder** [comment]
One of my favorite conferences. Full of 10 minute talks by people who love playing with tech for the fun of it. Very friendly!
