### ISSUE TITLE
2017-03-24 Scala Up North

### ISSUE THREAD

**Issue by alejandrolujan** [catehstn/technically-speaking#305]
### Scala Up North
The first and only Scala conference in Canada. 
 
Event date: 2017-07-21 to 2017-07-22
Location: Vancouver, Canada.
Submission deadline: 2017-03-24
Travel expenses covered: No
[Scala Up North website](http://scalaupnorth.com)
[CFP](http://scalaupnorth.com/cfp.html)
[@ScalaUpNorth](https://twitter.com/ScalaUpNorth)

**Comment by chiuki** [comment]
Sorry we don't include conferences that flat out say no to helping speakers. We understand that there may not be budget to support everyone, but we prefer to include conferences that at least make an effort on a case-by-case basis.

**Comment by alejandrolujan** [comment]
I understand. We aim to have this in place - hopefully next year. We'll try again then.
