### ISSUE TITLE
2017-04-14: 360|iDev

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#307]
### 360|iDev
*The Leading indie iOS/Mac (and watchOS, and tvOS) Developer conference*
 
Event date: August 13 - 16, 2017
Location: Denver, CO
Submission deadline: April 14, 2017
Travel expenses covered: Hotel. Airfare available if needed.
[360idev.com](https://360idev.com/)
[papercall.io/360idev-2017](https://www.papercall.io/360idev-2017)
[@360idev](https://twitter.com/360idev)

**Comment by jwilker** [comment]
Can we include this quote. 
“I love the diversity of the peer group of speakers at 360iDev. Since everyone goes through the CFP process, this conference features speakers that you wouldn't see at a lot of other iOS focused conferences where the majority of speakers are invited.”
										Benjamin Encz

**Comment by chiuki** [comment]
@jwilker Thanks for the quote! I assume that's https://twitter.com/benjaminencz? (We usually link the quotes to their twitter account)

**Comment by jwilker** [comment]
Ah yes, that’s him. Awesome

John Wilker
Founder, 360|Conferences
(720) 381-2370
twitter: jwilker
Chicago Roboto | 360|iDev | 360IAnDev

Remember that bad times, are just times that are bad.
