### ISSUE TITLE
You plan to have this talk? How about no.

### ISSUE THREAD

**Issue by shem8** [catehstn/technically-speaking#310]
URL: https://medium.com/@shemag8/you-plan-to-have-this-talk-how-about-no-bd7317f30f43#.ubhzb9ct1
Author name: Shem Magnezi
Author twitter handle: @shem8

Some partial list of mistakes people is doing when trying to come up with ideas for talks, and how to fix it and make those talks more effective.

**Comment by chiuki** [comment]
Thanks for submitting. I don't feel comfortable including this post in the newsletter though. The title is really negative, and the rest of the post is much stronger in striking down the talks than giving helpful suggestions.

**Comment by shem8** [comment]
fair enough :+1:
