### ISSUE TITLE
The Lead Developer UK 2017 Scholarship Scheme

### ISSUE THREAD

**Issue by jonnyblackler** [catehstn/technically-speaking#311]
[The Lead Developer UK 2017](http://2017.theleaddeveloper.com/), the 2-day conference for tech leads, is running a scholarship scheme to support individuals from underrepresented groups in tech and those facing economic or social hardship. Learn more and apply [here](http://2017.theleaddeveloper.com/blog/2017-01-27-the-lead-developer-uk-2017-scholarship-scheme). Deadline: 28 April.

Conference: [@TheLeadDev](https://twitter.com/TheLeadDev)
Organiser: [@whiteoctevents](https://twitter.com/whiteoctevents)

**Comment by catehstn** [comment]
Ahh so sorry we missed this @jonnyblackler.
