### ISSUE TITLE
Content: "What Makes a Coder" by Omoju Miller

### ISSUE THREAD

**Issue by nitya** [catehstn/technically-speaking#318]
> URL

https://codeascraft.com/speakers/omoju-miller-what-really-makes-a-coder-a-machine-learning-approach-to-the-tech-pipeline/

> Talk title

What really makes a coder? A machine learning approach to the tech pipeline

> Author name

Omoju Miller

> Twitter Handle

@omojumiller

> My Twitter Handle

@nitya
Your twitter handle (optional)

> About the talk

Talk was part of the Etsy "Code As Craft" series from Feb 7, 2017. 
From their abstract: 

```
There is a myth in technology that talent stems from innate ability. 
Really though it’s a process of learning and hard work.

As seen through history, technology can destabilize the jobs market. 
This begs the question: 
what are truck drivers going to do in the age of driverless cars? 

Omoju Miller’s work puts forward the idea that we can scale adult technical education for 
workforce readiness while leveraging that opportunity to equalize participation.
```
> What I loved about it

Omoju is a fantastic and engaging speaker - and her talk literally backs up every insight with data and analysis, which makes it hard to refute the findings. Three quotes that made me take notice (and that have stuck with me ever since):

 1. _People left in CS are < 30% of population. Self-selecting won't scale for mass re-training_ - making the case that if we wait for people to "choose" CS then we will never have the mass of skilled workers that we will need for the tech and automation driven future that is coming fast.

2. _The importance of "belonging" is critical_ - such a simple statement but with such powerful impact. She cites a survey that showed even Berkeley students in CS suffered from a sense of not belonging in a class of their CS peers.

3. _Peanuts & Science vs. Pizza & Beer_ - making the case that we need to rethink the social implications and cultures of computing before we can have an environment where everyone feels like they belong.

If there is one thing I would take away from this talk, it is that we, each and every one of us in this industry, need to ask what "belonging" means to different genders, ethnicities, ages and levels of experience - and ask whether the work environment provides enough flexibility to support those needs.

**Comment by catehstn** [comment]
Included in #317
