### ISSUE TITLE
2017-05-01: KotlinConf

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#321]
### KotlinConf
*A conference about everything Kotlin, brought to you by JetBrains* 
 
Event date: November 2 - 3, 2017
Location: San Francisco, CA
Submission deadline: May 1, 2017
Travel expenses covered: Yes
[kotlinconf.com](https://kotlinconf.com/)
[sessionize.com/kotlinconf](https://sessionize.com/kotlinconf/)
[@kotlinconf](https://twitter.com/kotlinconf)

**Comment by catehstn** [comment]
Missed cfp deadline.
