### ISSUE TITLE
2017-04-14: EuRuKo

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#326]
### EuRuKo
*European Ruby Conference* 
 
Event date: September 29 - 30, 2017
Location: Budapest, Hungary
Submission deadline: April 14, 2017
Travel expenses covered: [As much as they can, dependent on sponsors](http://pastebin.com/DfQ1K1nP)
[euruko2017.org](https://euruko2017.org/)
[euruko2017.org/speakers](https://euruko2017.org/speakers/)
[@EuRuKo](https://twitter.com/EuRuKo)

**Comment by amrabdelwahab** [comment]
Yes That's perfect thanks a lot @chiuki
