### ISSUE TITLE
ExpertWomen

### ISSUE THREAD

**Issue by acorey** [catehstn/technically-speaking#342]
If you are submitting a link, please include:
---------------------------------------------
URL: http://expertwomen.ca
Author name: n/a
Author twitter handle: ExpertWomenCA
Your twitter handle andreacorey
Short description of what you loved about it:
 
A new tool to find female experts in a range of topics.   "Helping journalists, conference planners and others find the expert women they need. A project of @InformedOps"

Looks like it could be an interesting place for your mailing list recipients to post a profile.  There aren't many experts in software dev listed at present, but the category exists.

**Comment by catehstn** [comment]
Thanks for suggesting this - we do really appreciate it. There have been a  number of these kinds of directory initiatives, and we've not found them to be particularly effective so we don't include them.
