### ISSUE TITLE
2017-05-01: SIGNAL London 2017

### ISSUE THREAD

**Issue by mplacona** [catehstn/technically-speaking#351]
### SIGNAL London 2017
*SIGNAL London – Twilio's annual developer conference* 
 
Event date: September 19, 2017
Location: London, England
Submission deadline: May 1st, 2017
Travel expenses covered: Case-by-case basis. We'll do our best to help you out
[Signal London](https://www.twilio.com/signal/london)
[cfp](https://www.papercall.io/twilio-signal-london)
[@signalconf](https://twitter.com/signalconf?lang=en)

**Comment by chiuki** [comment]
Closing since the CFP deadline has passed.

**Comment by mplacona** [comment]
@chiuki we've extended the CFP. Any chance we could get in for the next weeks newsletter?

Thanks
