### ISSUE TITLE
Women and being interrupted

### ISSUE THREAD

**Issue by catehstn** [catehstn/technically-speaking#354]
"I saw this discussion on Twitter recently about how women can amplify each other in meetings, along with a Donald Trump-style “interruption tracker app”, wondering whether the only authoritative voice as a woman in a male-dominated environment is “the Mum voice”: [https://twitter.com/Delafina777/status/846600201108303872](https://twitter.com/Delafina777/status/846600201108303872)

It feels as if we’re mid-way through this discussion at the moment, in a problematic time and space, and these strategies are partly helpful in the short term but also point to massive structural issues that have to be addressed long term, in the way we socialise our children from a young age."

**Comment by rosieclarke** [comment]
Thanks for sharing this, Cate - my Twitter handle is [@rosieclarke](www.twitter.com/rosieclarke).
