### ISSUE TITLE
2017-05-23: FrOSCon

### ISSUE THREAD

**Issue by ScottyTM** [catehstn/technically-speaking#362]
### FrOSCon
*Free and Open Source Software Conference*
 
Event date: August 19th - 20th 2017
Location: St. Augustin, Germany
Submission deadline: May 23rd 2017
Travel expenses covered: Ask. “In special cases we might be able to help you with your travel expenses and we continue trying to find sponsors for this. Please get in touch with us.”
[FrOSCon](http://www.froscon.org)
[CfP](http://www.froscon.de/1/cfp)
[@ScottyTM](http://twitter.com/froscon)

**Comment by chiuki** [comment]
Closing since the CFP deadline has passed.
