### ISSUE TITLE
2017-05-31: RubyConf Colombia

### ISSUE THREAD

**Issue by sebasoga** [catehstn/technically-speaking#367]
### RubyConf Colombia
*Premier Ruby conference in Latin America, consisting in 2 full days of talks.* 
 
Event date: September 8-9th, 2017
Location: Medellín, Colombia
Submission deadline: May 31st, 2017
Travel expenses covered: Yes, accommodation for 3 nights and up-to USD $1000 for flights.

* [Website](http://www.rubyconf.co/)
* [CFP](https://www.papercall.io/rubyconfco-2017)
* [@RubyConfCo](https://twitter.com/rubyconfco)

**Comment by sebasoga** [comment]
We also run a [Diversity Scholarship Program](https://medium.com/rubyconf-colombia/diversity-scholarship-program-e8da16c34995) which we encourage people to apply to or to donate to!

**Comment by catehstn** [comment]
"Cate spoke last year and had a great time! Medellín is a beautiful city, and a fantastic place to explore."
