### ISSUE TITLE
2017-05-29 : BSidesChicago

### ISSUE THREAD

**Issue by margaretvaltie** [catehstn/technically-speaking#371]
### BSides Chicago
*community information security* 
 
Event date: July 15, 2017
Location: Chicago, IL USA
Submission deadline: May 29, 2017
Travel expenses covered: No
[BSidesChicago.org](https://bsideschicago.org/)
[Google Form](https://docs.google.com/a/cohesive.net/forms/d/e/1FAIpQLSfzDMHpuNVROAF8E7OGpEPH4mp5dDCSF9DKyowUBkA_xjHxJg/viewform?c=0&w=1)
[@BSidesChicago](https://twitter.com/BSidesChicago)

**Comment by chiuki** [comment]
Sorry we require conferences to have a code of conduct, and we don't include conferences that flat out say no to helping speakers. We understand that there may not be budget to support everyone, but we prefer to include conferences that at least make an effort on a case-by-case basis.

**Comment by margaretvaltie** [comment]
Ah, you wrote that in the form and I skipped over that.
I'm helping organize BSides Chi and we've still got work to do on the
website and CFP process. CoC is moving up the list!
Thank you for your work creating this newsletter.

*Margaret Valtierra*
MargaretMValtierra@gmail.com
615.516.7850
