### ISSUE TITLE
Public Speaking Workshop in Berlin @ UIKonf

### ISSUE THREAD

**Issue by jeffwatkins** [catehstn/technically-speaking#376]
If you'd like to kick your public speaking skills up to the next level and are planning to attend UIKonf in Berlin or are in the area, join us for the public speaking workshop on Saturday, 13 May. We'll focus on building skills and preparing 5-minute lightning talks.

Every student receives a Kensington presentation remote and a link to download a recording of their presentation.

We're offering discounted tickets for women and under-represented people in the industry.

http://uikonf.com/workshops

**Comment by catehstn** [comment]
So sorry we missed this @jeffwatkins !
