### ISSUE TITLE
Finding "developer happiness" through Write/Speak/Code

### ISSUE THREAD

**Issue by hilarysk** [catehstn/technically-speaking#377]
**URL:** https://tenforward.consulting/blog/finding-my-version-of-developer-happiness-through-Write-Speak-Code

**Author name:** Hilary Stohs-Krause

**Author twitter handle:** hilarysk

**Description:** In the Ruby community, we talk a lot about "developer happiness." As someone relatively new to tech (I've been full-time for only two years), I didn't know what developer happiness would look like to me, specifically. Thanks to last year's Write/Speak/Code, I have a much better idea.

**Comment by catehstn** [comment]
Closed in #379
