### ISSUE TITLE
2017-06-23: php[world] 2017

### ISSUE THREAD

**Issue by EliW** [catehstn/technically-speaking#384]
### php[world] 2017
BRINGING THE ENTIRE WORLD OF PHP CLOSER TOGETHER… — 4th Annual Edition
 
Event date: November 15-16, 2017
Location: Washington, D.C.
Submission deadline: June 23rd, 2017
Travel expenses covered: Yes
[world.phparch.com](https://world.phparch.com)
[world.phparch.com/call-for-speakers](https://world.phparch.com/call-for-speakers)
[@phparch](https://twitter.com/phparch)

**Comment by catehstn** [comment]
Dupe of #404
