### ISSUE TITLE
2016-05-30: PostgresOpen Silicon Valley

### ISSUE THREAD

**Issue by craigkerstiens** [catehstn/technically-speaking#392]
### PostgresOpen Silicon Valley

PostgresOpen Silicon Valley is a non–profit, community–run conference series in the United States focused on business users, database professionals and developers of PostgreSQL, the open source database. This year PostgresOpen has combined forces with PGConf Silicon Valley to bring together two large Postgres conferences to create an even larger more exciting event.
 
Event date: September 6-8
Location: San Francisco, CA
Submission deadline: May 30, 2017
Travel expenses covered: No
[conf link](https://2017.postgresopen.org/)
[cfp](https://2017.postgresopen.org/callforpapers/)
[@conftwitterhandle](https://www.twitter.com/postgresopen)

**Comment by chiuki** [comment]
Sorry we don't include conferences that flat out say no to helping speakers. We understand that there may not be budget to support everyone, but we prefer to include conferences that at least make an effort on a case-by-case basis.
