### ISSUE TITLE
How I Create Talks

### ISSUE THREAD

**Issue by catehstn** [catehstn/technically-speaking#414]
Helpful blogpost from [@micheletitolo](http://twitter.com/micheletitolo) on how she prepares a talk and how that process has changed over time [[read it](https://michele.io/how-i-create-talks/)][tweet it]. We love this point, "There’s no “right” way to create a talk, just like there’s no right way to take a picture or write a book. Finding a good process and useful tools takes time, and I believe it’s an endeavor worth doing if you want to better your skills at presenting."

**Comment by camilleacey** [comment]
I already added this to the newsletter. Should I use your version instead?
