### ISSUE TITLE
2017-08-20: J-Fall

### ISSUE THREAD

**Issue by lvdpal** [catehstn/technically-speaking#417]
### J-Fall
*the biggest Java conference of the Netherlands* 
 
Event date: November 2, 2017
Location: Ede, the Netherlands
Submission deadline: August 20, 2017
Travel expenses covered: No
[http://jfall.nl/]
[http://nljugcfp.nl/]
[@nljug]

**Comment by catehstn** [comment]
Closing due to: no provision for speaker travel.
