### ISSUE TITLE
Repo of Public Speaking tips

### ISSUE THREAD

**Issue by ChrisGuzman** [catehstn/technically-speaking#419]
URL: https://github.com/vmbrasseur/Public_Speaking
Author name: VM (Vicky) Brasseur
Author twitter handle (if available): https://twitter.com/vmbrasseur
Your twitter handle (optional)
Short description of what you loved about it: I love this growing list of resources and tips for public speakers and soon to be speakers! The repo is still growing and accepts anyone's PRs. It also references Technically Speaking,

Cheers to @vmbrasseur and @jberkus for organizing the repo!

**Comment by jberkus** [comment]
Thanks, but it was entirely @vmbrasseur's work.
