### ISSUE TITLE
2017-07-04 WebCamp Zagreb 2017

### ISSUE THREAD

**Issue by lmuzinic** [catehstn/technically-speaking#424]
### WebCamp Zagreb 2017
*Technology oriented conference for developers & designers* 
 
Event date: October 6th & 7th, 2017
Location: Zagreb, Croatia
Submission deadline: July 4th, 2017
Travel expenses covered: Yes for keynote speakers
[WebCamp Zagreb 2017](https://2017.webcampzg.org/)
[Submit a talk](https://2017.webcampzg.org/cfp/)
[@webcampzagreb](https://twitter.com/webcampzagreb)

**Comment by chiuki** [comment]
Closing since the CFP deadline has passed.
