### ISSUE TITLE
2017-07-14: TechSummit Washington D.C.

### ISSUE THREAD

**Issue by spoelwijk** [catehstn/technically-speaking#429]
### TechSummit Washington D.C.
*Building Reliability at Scale* 
 
Event date: November 2, 2017
Location: Washington D.C., United States
Submission deadline: July 14, 2017
Travel expenses covered: Yes
[techsummit.io](http://www.techsummit.io)
[techsummit.io/cfp](http://www.techsummit.io/cfp/)
[@techsummitio](http://twitter.com/techsummitio)

**Comment by chiuki** [comment]
Does this conference have a code of conduct?

**Comment by spoelwijk** [comment]
Yes it does: http://confcodeofconduct.com

**Comment by chiuki** [comment]
Where is it linked from the conference web site? Participants need to know about it.

**Comment by spoelwijk** [comment]
You are right @chiuki, normally it's right above the registration page so everyone sees it, but registration is not open yet. So for now i've added it already to http://www.techsummit.io/washington/ and to the CFP page as well!
