### ISSUE TITLE
2017-08-04: BuzzCOnf Technology Festival 2017

### ISSUE THREAD

**Issue by rickginer** [catehstn/technically-speaking#433]
### BuzzConf Technology Festival 2017
technology, Innovation, Family, Fun
The tech festival for all the family - Where all participants and presenters spend the weekend learning and playing in country Victoria
 
Event date: 1-3 Dec
Location: Ballan, Victoria, Australia
Submission deadline: 4 August 2017
Travel expenses covered: where possible
[conf link](https://buzzconf.io)
[cfp](https://buzzconf.io/call-for-presenters)
[@buzzconfio](https://twitter.com/buzzconfio)

**Comment by catehstn** [comment]
Can you expand on "where possible" please?

**Comment by rickginer** [comment]
How much we can allocate to help with travel expenses will depend on the amount of sponsorship we receive, and the travel expenses asked for. If someone asks for business flights from USA, it is unlikely. Train fare from Geelong is probably not going to be a problem, but we cannot guarantee anything at this stage.
