### ISSUE TITLE
2017-08-31: Mobilization

### ISSUE THREAD

**Issue by tasza** [catehstn/technically-speaking#443]
### Mobilization
*Mobilize for Mobilization. Android, iOS and HTML5* 
 
Event date: October 21, 2017
Location: Łódź, Poland
Submission deadline: August 31, 2017
Travel expenses covered: Yes
[2017.mobilization.pl](http://2017.mobilization.pl/)
[bit.ly/mobilization7-c4p](https://bit.ly/mobilization7-c4p)
[@mobilizationpl](@mobilizationpl)

Mobilization is a conference dedicated to mobile technologies. The main scope is development of mobile solutions aimed at smartphones and tablets, with particular interest in Android, iOS and HTML5.

**Comment by chiuki** [comment]
Thanks! You may want to add it to the repo for Android conferences as well:
https://androidstudygroup.github.io/conferences

**Comment by tasza** [comment]
Thank you @chiuki for the suggestion, I will!
