### ISSUE TITLE
Typo?  Omogeneity

### ISSUE THREAD

**Issue by mscheel** [catehstn/technically-speaking#446]
The July 4 newsletter had the word omogeneity in it.  Unfamiliar with it I looked it up and it might be a typo.

> A common occurrence, especially when it comes to addressing speaker omogeneity, 

It's the first item in link round up.  It's possible you were going for some derivative of homogenous.

Love the newsletter!  Great work!

**Comment by chiuki** [comment]
Thanks! Yes it was a typo for homogeneity. Since this is a newsletter we can't edit it, and it's too small a typo to send out a correction, so we'll leave it as is.
