### ISSUE TITLE
2017-11-03: PGConf Austin

### ISSUE THREAD

**Issue by dcerda** [catehstn/technically-speaking#458]
### PGConf Local: Austin 2017
 
Event date: November 3 - 4, 2017
Location: Austin, Texas
Submission deadline: August 20, 2017
Travel expenses covered: No
https://pgconf.us/conferences/Austin2017
https://pgconf.us/conferences/Austin2017/program/proposals
[@PGConfUS](https://twitter.com/PGConfUS)

The inaugural PGConf US Local: Austin Conference (PGConf Austin) will be held November 3 - 4, 2017, at the Norris Conference Center located in northwest Austin.
PGConf Austin 2017 is a 2-day, multi track conference and is a perfect opportunity for users, developers, business analysts and enthusiasts from the Southwest to amplify Postgres and participate with the Postgres community. 
Program tracks include Dev, Ops, Training, and Community. We welcome other open source communities who support Postgres integrations (Linux, Ubuntu, Python, etc.) to participate and contribute.

**Comment by chiuki** [comment]
Sorry we don't include conferences that flat out say no to helping speakers. We understand that there may not be budget to support everyone, but we prefer to include conferences that at least make an effort on a case-by-case basis.
