### ISSUE TITLE
2017-08-07: Rust Belt Rust

### ISSUE THREAD

**Issue by carols10cents** [catehstn/technically-speaking#466]
### Rust Belt Rust
*A conference for people of any level of Rust experience.* 
 
Event date: Oct 26 - 27, 2017
Location: Columbus, OH
Submission deadline: Mon Aug 7, 2017 at 5pm ET
Travel expenses covered: Yes
[rust-belt-rust.com](https://www.rust-belt-rust.com/)
[cfp.rust-belt-rust.com](http://cfp.rust-belt-rust.com/)
[@rustbeltrust](https://twitter.com/rustbeltrust)

Thank you! <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 62.50000000000001%;background-size:4900%" data-codepoints="2764"></span></span>

**Comment by chiuki** [comment]
The code of conduct page is showing 404 right now? https://www.rust-belt-rust.com/conduct

**Comment by chiuki** [comment]
Ah, looks like the link is http://www.rust-belt-rust.com/conduct.html. You probably want to update the link at the bottom of the homepage.

Another question, @carols10cents: where does it mention that travel expenses are covered?

**Comment by carols10cents** [comment]
Ooops, will fix that link! The travel expense covering is mentioned on http://cfp.rust-belt-rust.com/: 

> We cover the cost of ticket, flights, hotels, and visas for all speakers. If you purchase a ticket before finding out you're a speaker, we will reimburse you.

I'll add that to the home page as well!

**Comment by carols10cents** [comment]
Ok links should be fixed and both the home page beneath the "submit a proposal" button and the CFP page as mentioned in the previous comment have the same information about speaker travel costs. Is there somewhere else you would expect to see that information where it was missing?

**Comment by chiuki** [comment]
Sorry I don't know how I missed it. I scanned the CFP page and searched for the word "travel". What you have is fine, but if you want to improve it perhaps you move it to a header "Travel Expenses"?

**Comment by carols10cents** [comment]
I've updated the CFP page with a travel expenses header! Great suggestion, thank you!! ❤️
