### ISSUE TITLE
[Link] Controlling APK Size When Using Native Libraries

### ISSUE THREAD

**Issue by brijeshmasrani** [catehstn/technically-speaking#484]
URL - https://android.jlelse.eu/controlling-apk-size-when-using-native-libraries-45c6c0e5b70a

Author name - Brijesh Masrani
Author Twitter handle (if available) - twitter.com/brijeshmasrani

Description - Article contains details about native library integration and CPU architectures. If an app is using libraries like Realm/Facebook conceal this configuration can reduce apk size significantly.

**Comment by chiuki** [comment]
Not related to public speaking
