### ISSUE TITLE
[Link] Android O — What’s New For Users?

### ISSUE THREAD

**Issue by brijeshmasrani** [catehstn/technically-speaking#485]
URL - 
https://android.jlelse.eu/android-o-whats-new-for-users-part1-7c27b4eb560c
https://android.jlelse.eu/android-o-whats-new-for-users-part-2-52badc4b1b6f

Author name - Brijesh Masrani
Author twitter handle - twitter.com/brijeshmasrani

Description - Article contains all the details about Android O changes in latest Beta version.

**Comment by chiuki** [comment]
Not related to public speaking
