### ISSUE TITLE
2016-06-30: Code Mesh

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#52]
### Code Mesh 
*The Alternative Programming Conference, promoting revolutionary technologies in the software industry.*

Event date: November 2 - 4, 2016
Location: London, UK
Submission deadline: June 30, 2016
Travel expenses covered: [Yes](https://twitter.com/CodeMeshIO/status/740853283733016577)
[http://www.codemesh.io](http://www.codemesh.io)
[http://goo.gl/forms/MLfYcrgjv9xHXdmp1](http://goo.gl/forms/MLfYcrgjv9xHXdmp1)
[@CodeMeshIO](https://twitter.com/CodeMeshIO)

**Comment by catehstn** [comment]
Closed in #59
