### ISSUE TITLE
2016-06-30: elm-conf

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#53]
### elm-conf
*The Elm programming language and its libraries* 
 
Event date: September 15, 2016
Location: St Louis, MO (colocated with [Strange Loop](http://www.thestrangeloop.com))
Submission deadline: June 30, 2016
Travel expenses covered: Yes
[https://www.elm-conf.us](https://www.elm-conf.us)
[https://www.elm-conf.us/speaker](https://www.elm-conf.us/speaker)
[@ElmConf](https://twitter.com/ElmConf)

**Comment by catehstn** [comment]
Closed in #59
