### ISSUE TITLE
Contributing to Open Source as a Non-Developer

### ISSUE THREAD

**Issue by kkoppenhaver** [catehstn/technically-speaking#546]
http://alphaparticle.com/contributing-to-open-source/
Keanan Koppenhaver
[@kkoppenhaver](https://twitter.com/kkoppenhaver)

This is the blog post version of a talk I gave at WordCamp LAX. 

Lots of non-developers feel intimidated by the thought of contributing to open source because they feel they need to write code to do so.  But contributing to repos (like Technically Speaking) can often be done without writing a line of code.  In this talk, we looked at the open source community, why it's important, the anatomy of a pull request and how to make one.  

Slides: https://www.slideshare.net/kkoppenhaver/contributing-to-open-source-as-a-non-developer-wclax/

Video: Coming soon on WordPress.tv, I'll post the link on this issue when it's available.

**Comment by catehstn** [comment]
Thanks for submitting this! It doesn't seem related to public speaking though, so I'm closing it.
