### ISSUE TITLE
2017-11-17: RedisConf 18

### ISSUE THREAD

**Issue by tague** [catehstn/technically-speaking#561]
### RedisConf 18
The largest gathering of Redis users and experts.

Event date: April 24-26, 2018
Location: San Francisco, CA
Submission deadline: Nov. 17th 2017
Travel expenses covered: No
[yourconf.com] http://redisconf.com/
[cfp.yourconf.com] https://myeventi.events/redisconf18/cfp/
[@conftwitterhandle] @redisconf

**Comment by chiuki** [comment]
Sorry we don't include conferences that flat out say no to helping speakers. We understand that there may not be budget to support everyone, but we prefer to include conferences that at least make an effort on a case-by-case basis.
