### ISSUE TITLE
2017-12-08: IndexConf

### ISSUE THREAD

**Issue by emckean** [catehstn/technically-speaking#576]
### IndexConf
An open, developer community event. Learn first-hand from leading industry experts how to develop the future of secure, smart and scalable software solutions.

Event date: FEB 20–22, 2018
Location: San Francisco, California
Submission deadline: 8 December 2017
Travel expenses covered: No
[IndexConf](http://indexconf.com)
[CFP](https://www-01.ibm.com/events/wwe/indexconf/indexconf18.nsf/Speaker.xsp?S_VCPI=dw-_-social1711-_-redirect-_-indexconf)

**Comment by chiuki** [comment]
Sorry we don't include conferences that flat out say no to helping speakers. We understand that there may not be budget to support everyone, but we prefer to include conferences that at least make an effort on a case-by-case basis.

**Comment by emckean** [comment]
Thanks Chiu! I'm still working on getting speaker travel support out of IBM but I don't have a yes yet, so I thought it was safer to say no. :( 

Thank you for giving me ammunition to bring to the funding team so that I can say we will not be able to spread the word about this new conference unless we can offer speaker travel support. :)
