### ISSUE TITLE
2016-07-29: BuzzConf

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#64]
### BuzzConf
*A cutting edge, technology, futurism, and innovation conference at a scenic campground* 
 
Event date: November 25 - 27, 2016
Location: Ballan, Victoria, Australia
Submission deadline: July 29, 2016
Travel expenses covered: "We may be able to help in some special cases"
[https://buzzconf.io/festival-2016](https://buzzconf.io/festival-2016)
[https://buzzconf.io/festival-2016/call-for-presenters](https://buzzconf.io/festival-2016/call-for-presenters)
[@buzzconfio](twitter.com/buzzconfio)

**Comment by abelotti** [comment]
I had an amazing time at Buzzconf. Not only speaking to an engaging audience that asked lots of intelligent questions, but also hanging out with everyone over the weekend. The fact that Buzzconf is a festival and we get to retreat to an isolated location, making it more personable and fun. The entertainment, the bonfires, the marshmallows, the new friendships, it all comes together to make Buzzconf an unique experience.
