### ISSUE TITLE
J-Fall 2016

### ISSUE THREAD

**Issue by lvdpal** [catehstn/technically-speaking#68]
J-Fall 2016
the biggest Java conference of the Netherlands
 
Event date: November 3 2016
Location: Ede, the Netherlands
Submission deadline: August 21
Travel expenses covered: No
http://www.nljug.org/jfall/2016/
[Call for papers](http://www.nljugcfp.nl/)
@nljug

**Comment by chiuki** [comment]
@lvdpal Does J-Fall have a code of conduct?

**Comment by lvdpal** [comment]
@chiuki I've just asked the organizers. Will let you know.

**Comment by chiuki** [comment]
Closing since the CFP deadline has passed.

**Comment by lvdpal** [comment]
Yeah, sorry about that. They never got back to me about that CoC before the
deadline. There will apparently be one... Oh well, better luck next year.
