### ISSUE TITLE
2016-07-17: SAINTCON

### ISSUE THREAD

**Issue by SecureUtah** [catehstn/technically-speaking#74]
### SAINTCON
*Utah's Largest Security Conference* 
 
Event date: October 11-14, 2016
Location: Provo, Utah
Submission deadline: July 17, 2016
Travel expenses covered: Limited - contact saintcon@utahsaint.org for details
https://saintcon.org
[Call For Papers](https://www.saintcon.org/cfp/)
[Call for Trainers](https://www.saintcon.org/cft/) - selected trainers receive compensation for training and for each student attending
[Twitter](https://twitter.com/saintcon)

[About](https://www.saintcon.org/about/)
[FAQs](https://www.saintcon.org/faq/)

SAINTCON is Utah's largest annual technology security conference, run by geeks for geeks. Last year sold out with 575 attendees and this year it's being held in a new venue with capacity for over 1000. SAINTCON welcomes everyone of all skill levels and is family friendly - no doing shots on stage, using strong language in presentations is discouraged, and NSFW material is prohibited. The badges are custom-design and interactive, there are Hardware Hacking and Lock Picking villages, and the top scores in the Hacker's Challenge trivia/puzzle/CTF-style game receive prizes.

**Comment by SecureUtah** [comment]
Background info -

SAINTCON is Utah's largest annual technology security conference, run by geeks for geeks. Last year sold out with 575 attendees and this year it's being held in a new venue with capacity for over 1000. SAINTCON welcomes everyone of all skill levels and is family friendly - no doing shots on stage, using strong language in presentations is discouraged, and NSFW material is prohibited. The badges are custom-design and interactive, there are Hardware Hacking and Lock Picking villages, and the top scores in the Hacker's Challenge trivia/puzzle/CTF-style game receive prizes.

**Comment by chiuki** [comment]
We only recommend conference with Code of Conduct. Does SAINTCON have one?

**Comment by SecureUtah** [comment]
Unfortunately, not yet.  I wasn't aware of that requirement before submitting this issue, I apologize for missing it.

I'll get in touch with the conference committee and urge them to prepare a CoC.  I'm sure it won't be done before the CFP closes but I expect that it can be completed before the event in October.

**Comment by chiuki** [comment]
Closing since the CFP deadline has passed.
