### ISSUE TITLE
Employee Evangelism: Make Your Team Badass

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#75]
http://missgeeky.com/2016/07/07/employee-evangelism-make-team-badass

by [@mseckington](https://twitter.com/mseckington/status/751106537414852608)

"Two weeks ago I gave a talk at The Lead Developer called How To Succeed at Hiring Without Really Trying. This is pretty much the blog post version of my script/speaker’s notes for it! Check out the [full slides](http://www.slideshare.net/mseckington/how-to-succeed-at-hiring-without-really-trying)."

**Comment by catehstn** [comment]
Included in #79
