### ISSUE TITLE
Moderating my first panel - Ask an Android Developer

### ISSUE THREAD

**Issue by chiuki** [catehstn/technically-speaking#78]
http://www.yprabhu.com/2016/07/moderating-my-first-panel-ask-android.html

by [@yashvprabhu](https://twitter.com/yashvprabhu)

Mentions:
- http://www.catehuston.com/blog/2015/12/14/moderating-my-first-panel
- https://www.amazon.com/Eloquent-Womans-Guide-Moderating-Panels-ebook/dp/B00T58GIFO

**Comment by catehstn** [comment]
Referenced in #144
