### ISSUE TITLE
2016-07-31: MKE DOT NET

### ISSUE THREAD

**Issue by pleepleus88** [catehstn/technically-speaking#85]
### MKE DOT NET
*MKE DOT NET is a one-day development conference in the Milwaukee area designed to bring together .NET developers from the Midwest to explore new ideas, code, share knowledge and discover best practices.* 
 
Event date: October 29, 2016
Location: Milwaukee, WI
Submission deadline: July 31, 2016
Travel expenses covered: [Case-by-case basis](https://github.com/catehstn/technically-speaking/issues/85#issuecomment-233348612)
[http://www.mkedotnet.com](http://www.mkedotnet.com)
[CFP](http://goo.gl/forms/w3R8zyxMoJ)

**Comment by pleepleus88** [comment]
Apologies for the late notice on this one - I only recently discovered the newsletter (which is awesome, by the way). If you are able to share it, great, thank you! If not, I understand.

**Comment by chiuki** [comment]
We require conferences to have code of conduct, and give preference to those that cover travel expenses for speakers. Does MKE DOT NET have a code of conduct?

**Comment by pleepleus88** [comment]
We do have a code of conduct, we just don't have it up on the site. I've attached it, but if you require it to be on the site I can work on getting it out there today. 

I've also been informed that we do cover travel expenses on a case-by-case basis, we just can't cover them all. 

[MKEDOTNET-CodeofConduct.pdf](https://github.com/catehstn/technically-speaking/files/369309/MKEDOTNET-CodeofConduct.pdf)

**Comment by chiuki** [comment]
Yes, please put it on the site. Thanks!

**Comment by pleepleus88** [comment]
All set. 
[Code of Conduct](http://www.centare.com/mke-dot-net-code-of-conduct/)

Thanks for pushing us to get that out there.
