### ISSUE TITLE
2016-08-01: Tech Exeter 2016

### ISSUE THREAD

**Issue by sophiedennis** [catehstn/technically-speaking#94]
### Tech Exeter 2016
*The South West's grassroots tech conference with an inclusive, community ethos, and friendly, welcoming vibe.* 
 
Event date: October 8, 2016
Location: Exeter, UK
Submission deadline: August 1, 2016
Travel expenses covered: Yes, on request.
[techexeter.uk/conference](https://techexeter.uk/conference/)
[techexeter.uk/conference-call-for-speakers](https://techexeter.uk/conference-call-for-speakers/)
[@TechExeter](https://twitter.com/TechExeter)

------------
ps our code of conduct is at https://techexeter.uk/code-of-conduct/

**Comment by chiuki** [comment]
Sorry I missed this because I was only looking at issues with the label CFP and the deadline would be over by next edition of the newsletter.
